name: build
on:
  pull_request
jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Gitleaks
        run: |
          docker run --rm --mount type=bind,source=${PWD},target=/path zricethezav/gitleaks:latest detect --source="/path" --no-git -r /path/finding.json --redact -v
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/
